In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

### since the output variable is Goal- churn or no churn TRIAL AND ERROR between logistic regression ,SVM ,Randomforest

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from collections import Counter
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,recall_score,precision_score

/Users/ashok/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [3]:
df= pd.read_csv('df_after_scale.csv')

In [4]:
X = df.drop('Churn',axis=1)

In [5]:
X.head()

State   Acc_len  Area_code  Int_plan  Vmail_plan  Vmail_message   Day_min  \
0      0  0.690901        415         0           1       1.261885  1.568293   
1      0  0.160503        415         0           1       1.335463 -0.349166   
2      0  0.918214        415         0           0      -0.577587  1.166275   
3      0 -0.420409        408         1           0      -0.577587  2.203741   
4      0 -0.647723        415         1           0      -0.577587 -0.254682   

   Day_calls  Day_charge  Eve_mins  Eve_calls  Eve_charge  Night_mins  \
0   0.500261    1.568569 -0.059921  -0.059527   -0.059742    0.872135   
1   1.154156   -0.349447 -0.097506   0.142298   -0.096978    1.064069   
2   0.701460    1.166439 -1.567294   0.495492   -1.567818   -0.752381   
3  -1.461423    2.203911 -2.740354  -0.614545   -2.740765   -0.073686   
4   0.651160   -0.254636 -1.031207   1.100966   -1.030217   -0.271556   

   Night_calls  Night_charge  Int_mins  Int_calls  Int_charge  Custserv_calls  
0    -0.448712      0.871418 -0.101301  -0.583487   -0.102005       -0.433885  
1     0.153308      1.064889  1.240707  -0.583487    1.241481       -0.433885  
2     0.203477     -0.751101  0.696649   0.230398    0.690651       -1.199068  
3    -0.549048     -0.073952 -1.334498   1.044284   -1.338013        0.331298  
4     1.056338     -0.271820 -0.065031  -0.583487   -0.061701        1.096480

In [7]:
y=df.Churn

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=10)

In [9]:
print(X_train.shape)
print(X_test.shape)

(3231, 19)
(1386, 19)


In [10]:
print(Counter(y_train))
print(Counter(y_test))

Counter({0: 2761, 1: 470})
Counter({0: 1200, 1: 186})


In [11]:
#### SMOTING REQUIRED -since the ratio of churners and non-churners is not equal

In [12]:
sm = SMOTE()

In [13]:
X_train_sm,y_train_sm = sm.fit_sample(X_train,y_train)

In [16]:
# now the chuners and non chuners ratio is same in the output
print(Counter(y_train))
print(Counter(y_train_sm))


Counter({0: 2761, 1: 470})
Counter({0: 2761, 1: 2761})


## Logistic Regression

In [17]:
clf=LogisticRegression()
clf.fit(X_train_sm,y_train_sm)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [18]:
y_pred=clf.predict(X_test)

In [19]:
#checking accuracy score 

In [20]:
accuracy_score(y_test,y_pred)

0.7748917748917749

In [21]:
recall_score(y_test,y_pred)

0.7688172043010753

In [22]:
precision_score(y_test,y_pred)

0.3470873786407767

In [20]:
confusion_matrix(y_test,y_pred)

array([[935, 265],
       [ 43, 143]])

In [21]:
pd.crosstab(y_test,y_pred)

col_0    0    1
Churn          
0      935  265
1       43  143

In [22]:
print(classification_report(y_test,y_pred))

             precision    recall  f1-score   support

          0       0.96      0.78      0.86      1200
          1       0.35      0.77      0.48       186

avg / total       0.87      0.78      0.81      1386



### For the LR though the recall is 78% the precision score is very less 

## Support vector Machine

In [23]:
svc= SVC()

In [24]:
svc.fit(X_train_sm,y_train_sm)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [25]:
y_pred_svc= svc.predict(X_test)

In [26]:
accuracy_score(y_test,y_pred_svc)

0.8795093795093795

In [27]:
print(classification_report(y_test,y_pred_svc))

             precision    recall  f1-score   support

          0       0.95      0.90      0.93      1200
          1       0.54      0.72      0.62       186

avg / total       0.90      0.88      0.89      1386



In [28]:
confusion_matrix(y_test,y_pred_svc)

array([[1085,  115],
       [  52,  134]])

In [29]:
pd.crosstab(y_test,y_pred)

col_0    0    1
Churn          
0      931  269
1       43  143

### Random forest 

In [30]:
model = RandomForestClassifier(random_state=5,n_estimators=100,max_depth=15)

In [31]:
model.fit(X_train_sm,y_train_sm)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=15, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=5, verbose=0, warm_start=False)

In [32]:
model.feature_importances_

array([0.00046011, 0.02333284, 0.00613598, 0.16952228, 0.03668814,
       0.02955889, 0.1159341 , 0.02393662, 0.12245241, 0.04980709,
       0.02104045, 0.04817107, 0.03240549, 0.02155054, 0.0309621 ,
       0.03079055, 0.0560114 , 0.02928724, 0.15195269])

In [33]:
y_pred_rf= model.predict(X_test)

In [34]:
print(classification_report(y_test,y_pred_rf))

             precision    recall  f1-score   support

          0       0.97      0.96      0.97      1200
          1       0.78      0.81      0.80       186

avg / total       0.95      0.94      0.94      1386



In [35]:
accuracy_score(y_test,y_pred_rf)

0.9444444444444444

In [36]:
pd.crosstab(y_test,y_pred_rf)

col_0     0    1
Churn           
0      1158   42
1        35  151

###  Random forest gives best results for all the metrics as compared to LR and SVM